server:
  name: "Dusk"
  world_name : "Keth'volar"
  seed: "Mud"
  max_cpu_cores: 0
  ports: [4000, 4001]
  max_players: 100
  idle_timeout_minutes: 30
  log_level: "Debug"
paths:
  root_data_dir: "_data"
  player_data : "players"
  world_files: "world"
  localization: "localization"
  logs: "logs"
  templates: "templates"
  races: "races"
  classes: "classes"
core:
  tick_rate : 100
  default_area: "medical_bay_alpha"
  default_room: "3001"
logging:
  log_dir: "logs"
  log_file: "mud.log"
  max_size: 80
  max_backups: 5
  max_age: 30
  compress: true
  #Behavior
  level: 1
  enable_console: true
  enable_structured: true
  enable_game_logs: true
  enable_admin_logs: true
  enable_system_logs: true
  enable_error_logs: true
